# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag


# Setup
title:            Xuefei Li
subtitle:         李雪霏
description:      "Ph.D. student, ECSE, RPI"
email:            "Email: lix46[at]rpi.edu"
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
